// Code generated by go generate; DO NOT EDIT.
// Code generated by go generate; DO NOT EDIT.
// Code generated by go generate; DO NOT EDIT.

package bsp

import "blue/commands"

const cmdLen = 6

// system -----------------------------
const (
	VERSION Header = 1 + TypeSystem
)

// db -----------------------------
const (
	DEL Header = 1 + TypeDB
	EXPIRE Header = 2 + TypeDB
	USE Header = 3 + TypeDB
)

// number -----------------------------
const (
	NGET Header = 1 + TypeNumber
	NSET Header = 2 + TypeNumber
)

// string -----------------------------
const (
)

// list -----------------------------
const (
)

// set -----------------------------
const (
)

// json -----------------------------
const (
)

var HandleMap = [...]string{
	DEL: "DEL",
	EXPIRE: "EXPIRE",
	NGET: "NGET",
	NSET: "NSET",
	USE: "USE",
	VERSION: "VERSION",
}

var HandleMap2 = map[string]Header{
	"DEL": DEL,
	"EXPIRE": EXPIRE,
	"NGET": NGET,
	"NSET": NSET,
	"USE": USE,
	"VERSION": VERSION,
}

var CommandsMap = [...]commands.Cmd{
	DEL: {Name:"DEL",Summary: "Remove the specified keys", Group: "db", Arity: -1, Key: "list", Value: "", Arguments: []string{}},
	EXPIRE: {Name:"EXPIRE",Summary: "Set a key's time to live in seconds", Group: "db", Arity: 2, Key: "string", Value: "number", Arguments: []string{}},
	NGET: {Name:"NGET",Summary: "Returns the number value of a key.", Group: "number", Arity: 1, Key: "string", Value: "", Arguments: []string{}},
	NSET: {Name:"NSET",Summary: "Set the value of a number", Group: "number", Arity: 2, Key: "string", Value: "number", Arguments: []string{"expire"}},
	USE: {Name:"USE",Summary: "Uses a db.", Group: "db", Arity: 1, Key: "number", Value: "", Arguments: []string{}},
	VERSION: {Name:"VERSION",Summary: "Get the version of the system.", Group: "system", Arity: 0, Key: "", Value: "", Arguments: []string{}},
}

