// Code generated by go generate; DO NOT EDIT.
// Code generated by go generate; DO NOT EDIT.
// Code generated by go generate; DO NOT EDIT.

package bsp

import "blue/commands"

const cmdLen = 11

// list -----------------------------
const ()

// set -----------------------------
const ()

// json -----------------------------
const ()

// system -----------------------------
const (
	KVS     Header = 1 + TypeSystem
	VERSION Header = 2 + TypeSystem
)

// db -----------------------------
const (
	DEL    Header = 1 + TypeDB
	EXPIRE Header = 2 + TypeDB
	SELECT Header = 3 + TypeDB
)

// number -----------------------------
const (
	INCR Header = 1 + TypeNumber
	NGET Header = 2 + TypeNumber
	NSET Header = 3 + TypeNumber
)

// string -----------------------------
const (
	GET Header = 1 + TypeString
	LEN Header = 2 + TypeString
	SET Header = 3 + TypeString
)

var HandleMap = [...]string{
	DEL:     "DEL",
	EXPIRE:  "EXPIRE",
	GET:     "GET",
	INCR:    "INCR",
	KVS:     "KVS",
	LEN:     "LEN",
	NGET:    "NGET",
	NSET:    "NSET",
	SELECT:  "SELECT",
	SET:     "SET",
	VERSION: "VERSION",
}

var HandleMap2 = map[string]Header{
	"DEL":     DEL,
	"EXPIRE":  EXPIRE,
	"GET":     GET,
	"INCR":    INCR,
	"KVS":     KVS,
	"LEN":     LEN,
	"NGET":    NGET,
	"NSET":    NSET,
	"SELECT":  SELECT,
	"SET":     SET,
	"VERSION": VERSION,
}

var CommandsMap = [...]commands.Cmd{
	DEL:     {Name: "DEL", Summary: "Remove the specified keys", Group: "db", Arity: -1, Key: "list", Value: "", Arguments: []string{}},
	EXPIRE:  {Name: "EXPIRE", Summary: "Set a key's time to live in seconds", Group: "db", Arity: 2, Key: "string", Value: "number", Arguments: []string{}},
	GET:     {Name: "GET", Summary: "Returns the string value of a key.", Group: "string", Arity: 1, Key: "string", Value: "", Arguments: []string{}},
	INCR:    {Name: "INCR", Summary: "Increment the integer value of a key by the given amount", Group: "number", Arity: 2, Key: "string", Value: "number", Arguments: []string{}},
	KVS:     {Name: "KVS", Summary: "Returns all key-value pairs in the database", Group: "system", Arity: 0, Key: "", Value: "", Arguments: []string{}},
	LEN:     {Name: "LEN", Summary: "Returns the length of a string", Group: "string", Arity: 1, Key: "string", Value: "", Arguments: []string{}},
	NGET:    {Name: "NGET", Summary: "Returns the number value of a key.", Group: "number", Arity: 1, Key: "string", Value: "", Arguments: []string{}},
	NSET:    {Name: "NSET", Summary: "Set the value of a number", Group: "number", Arity: 2, Key: "string", Value: "number", Arguments: []string{"expire"}},
	SELECT:  {Name: "SELECT", Summary: "Select a db.", Group: "db", Arity: 1, Key: "number", Value: "", Arguments: []string{}},
	SET:     {Name: "SET", Summary: "Set the value of a key", Group: "string", Arity: 2, Key: "string", Value: "string", Arguments: []string{"expire"}},
	VERSION: {Name: "VERSION", Summary: "Get the version of the system.", Group: "system", Arity: 0, Key: "", Value: "", Arguments: []string{}},
}
